Switch to using ltd uploader action

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -14,7 +14,7 @@ jobs:
         with:
           python-version: 3.12
 
-      - name: Install dependancies and linters
+      - name: Install dependencies and linters
         run: |
           python -m pip install --upgrade pip
           python -m pip install uv
@@ -54,7 +54,6 @@ jobs:
           python -m pip install --upgrade pip
           python -m pip install uv
           python -m uv pip install --system -r docs/requirements.txt
-          python -m uv pip install --system ltd-conveyor
 
       - name: Pull existing images
         run: |
@@ -98,13 +97,23 @@ jobs:
         run: |
           make docs
 
-      - name: Upload documentation
-        if: ${{ github.event_name == 'push' }}
-        env:
-          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
-          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
-        run: |
-          ltd upload --product lsst-texmf --gh --dir docs/_build/html
+      # Only attempt documentation uploads for tagged releases and pull
+      # requests from ticket branches in the same repository.  This avoids
+      # version clutter in the docs and failures when a PR doesn't have access
+      # to secrets.
+      - name: Upload to LSST the Docs
+        uses: lsst-sqre/ltd-upload@v1
+        with:
+          project: "lsst-texmf"
+          dir: "docs/_build/html"
+          username: ${{ secrets.LTD_USERNAME }}
+          password: ${{ secrets.LTD_PASSWORD }}
+        if: >
+          (github.event_name == 'push' && github.ref_name == 'main')
+          || (github.event_name == 'workflow_dispatch')
+          || (github.event_name == 'pull_request'
+              && (startsWith(github.head_ref, 'tickets/')
+                  || startsWith(github.head_ref, 'u/')))
 
       - name: Log into Docker Hub
         if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
